"""Read, search, preview, and edit PDFs with pypdfium2

Docs: https://AnswerDotAI.github.io/fastpdfium/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['Match', 'pdfium']

# %% ../nbs/00_core.ipynb #6bd98d31
from fastcore.utils import *
from fastcore.meta import delegates
from PIL import Image, ImageDraw
from pypdfium2 import raw

import ctypes, io, pypdfium2 as pdfium

# %% ../nbs/00_core.ipynb #0eb03fa3
_all_ = ['pdfium']

# %% ../nbs/00_core.ipynb #c09e2049
if not hasattr(pdfium.PdfDocument, '_get_page'):
    pdfium.PdfDocument._get_page,pdfium.PdfDocument._new_page = pdfium.PdfDocument.get_page,pdfium.PdfDocument.new_page

@patch
def get_page(self:pdfium.PdfDocument, index):
    "Load page `index`, remembering it as `page.number`"
    pg = self._get_page(index)
    pg.number = index
    return pg

@patch
def new_page(self:pdfium.PdfDocument, width=595, height=842, index=None):
    "Append (or insert at `index`) a blank `width`x`height` point page, numbered like `get_page`"
    pg = self._new_page(width, height, index)
    pg.number = len(self)-1 if index is None else index
    return pg

# %% ../nbs/00_core.ipynb #bf70bc1b
@patch
def insert_text(
    self:pdfium.PdfPage,
    text, # Text to insert; newlines start new lines
    x=72, # Baseline start x, in points from the left
    y=72, # Baseline start y, in points from the top
    size=12, # Font size in points
    font='Helvetica', # Standard PDF font name
):
    "Insert `text` on the page at `x`,`y`"
    f = raw.FPDFText_LoadStandardFont(self.pdf.raw, font.encode())
    for j,line in enumerate(text.split('\n')):
        t = raw.FPDFPageObj_CreateTextObj(self.pdf.raw, f, size)
        buf = ctypes.create_string_buffer(line.encode('utf-16-le')+b'\x00\x00')
        raw.FPDFText_SetText(t, ctypes.cast(buf, ctypes.POINTER(ctypes.c_ushort)))
        raw.FPDFPageObj_Transform(t, 1, 0, 0, 1, x, self.get_height()-y-1.2*size*j)
        self.insert_obj(pdfium.PdfObject(t))
    self.gen_content()

# %% ../nbs/00_core.ipynb #633eb8e6
@patch
def draw_rect(
    self:pdfium.PdfPage,
    x0, y0, x1, y1, # Corners, in points from the top-left
    stroke=(255,0,0,255), # Stroke RGBA, 0-255 each (None for none)
    fill=None, # Fill RGBA (None for none)
    width=1, # Stroke width in points
):
    "Draw a rectangle from `x0`,`y0` to `x1`,`y1`"
    rc = raw.FPDFPageObj_CreateNewRect(x0, self.get_height()-y1, x1-x0, y1-y0)
    if stroke:
        raw.FPDFPageObj_SetStrokeColor(rc, *stroke)
        raw.FPDFPageObj_SetStrokeWidth(rc, width)
    if fill: raw.FPDFPageObj_SetFillColor(rc, *fill)
    raw.FPDFPath_SetDrawMode(rc, 1 if fill else 0, bool(stroke))
    self.insert_obj(pdfium.PdfObject(rc))
    self.gen_content()

# %% ../nbs/00_core.ipynb #d3f6b156
@patch
def insert_image(
    self:pdfium.PdfPage,
    img, # PIL image, or a path PIL can open
    x=72, # Left edge of the placed image, in points
    y=72, # Top edge of the placed image, in points
    w=None, # Width in points (default: pixel size; aspect kept if only one given)
    h=None, # Height in points
):
    "Place `img` at `x`,`y` (stored as JPEG)"
    if not isinstance(img, Image.Image): img = Image.open(img)
    if w is None and h is None: w,h = img.size
    elif w is None: w = h*img.width/img.height
    elif h is None: h = w*img.height/img.width
    buf = io.BytesIO()
    img.convert('RGB').save(buf, 'JPEG', quality=95)
    buf.seek(0)
    o = pdfium.PdfImage.new(self.pdf)
    o.load_jpeg(buf)
    o.set_matrix(pdfium.PdfMatrix(w, 0, 0, h, x, self.get_height()-y-h))
    self.insert_obj(o)
    self.gen_content()

# %% ../nbs/00_core.ipynb #400b2b4d
@patch
def tobytes(self:pdfium.PdfDocument)->bytes:
    "The document serialized as PDF bytes"
    buf = io.BytesIO()
    self.save(buf)
    return buf.getvalue()

# %% ../nbs/00_core.ipynb #c18daec1
@patch
def text(self:pdfium.PdfPage)->str:
    "Plain text of the page"
    return self.get_textpage().get_text_range().replace('\r\n', '\n')

# %% ../nbs/00_core.ipynb #3269a268
@patch
def text(self:pdfium.PdfDocument, pages=None)->str:
    "Plain text of `pages` (default: all), with `--- page N ---` separators"
    idxs = range(len(self)) if pages is None else pages
    return '\n'.join(f'--- page {i} ---\n{self[i].text().rstrip()}' for i in idxs)

# %% ../nbs/00_core.ipynb #312f68ed
class Match:
    "A search hit: chars `i` to `i+n` on `page`"
    def __init__(self, page, i, n, tp=None):
        store_attr('page,i,n')
        self.tp = tp or page.get_textpage()
    @property
    def text(self):
        "The matched text"
        return self.tp.get_text_range(self.i, self.n)
    def ctx(self, chars=40)->str:
        "The match marked with `**`, plus up to `chars` of surrounding text each side"
        s,e = max(0, self.i-chars), min(self.tp.count_chars(), self.i+self.n+chars)
        pre,post = self.tp.get_text_range(s, self.i-s), self.tp.get_text_range(self.i+self.n, e-self.i-self.n)
        return re.sub(r'[\r\n]+', ' ', f'{pre}**{self.text}**{post}')
    def rects(self):
        "Bounding boxes of the matched chars, in PDF (bottom-left origin) coords"
        return [self.tp.get_rect(k) for k in range(self.tp.count_rects(self.i, self.n))]
    def __repr__(self): return f'page {self.page.number}: {self.ctx()}'

@patch
def search(
    self:pdfium.PdfPage,
    q, # Text to search for
    match_case=False, # Case-sensitive?
    match_whole_word=False, # Whole words only?
    consecutive=False, # Allow overlapping matches?
)->list:
    "All `Match`es for `q` on this page"
    tp = self.get_textpage()
    srch = tp.search(q, match_case=match_case, match_whole_word=match_whole_word, consecutive=consecutive)
    res = []
    while (m := srch.get_next()) is not None: res.append(Match(self, *m, tp=tp))
    return res

@patch
@delegates(pdfium.PdfPage.search)
def search(self:pdfium.PdfDocument, q, **kwargs)->list:
    "All `Match`es for `q` across the document"
    return [m for p in self for m in p.search(q, **kwargs)]

# %% ../nbs/00_core.ipynb #79e4e9e6
@patch
def preview(
    self:pdfium.PdfPage,
    q=None, # Text whose matches to highlight
    dpi=150, # Render resolution
    crop=False, # Crop to the matched region?
    margin=24, # Points of context around a crop
):
    "Render to a PIL image, highlighting and optionally cropping to `q`'s matches"
    sc = dpi/72
    img = self.render(scale=sc).to_pil()
    if not q: return img
    ms = self.search(q)
    if not ms: raise ValueError(f'{q!r} not found on page {self.number}')
    h = self.get_height()
    rects = [rc for m in ms for rc in m.rects()]
    draw = ImageDraw.Draw(img)
    for l,b,r_,t in rects: draw.rectangle([(l-2)*sc, (h-t-2)*sc, (r_+2)*sc, (h-b+2)*sc], outline='red', width=max(1, round(dpi/50)))
    if crop:
        l,b = min(o[0] for o in rects)-margin, min(o[1] for o in rects)-margin
        r_,t = max(o[2] for o in rects)+margin, max(o[3] for o in rects)+margin
        img = img.crop((max(0, l*sc), max(0, (h-t)*sc), min(img.width, r_*sc), min(img.height, (h-b)*sc)))
    return img

# %% ../nbs/00_core.ipynb #f4b969ca
@patch
def _repr_png_(self:pdfium.PdfPage): return self.preview()._repr_png_()
